WanderWise-Inc/app

- .gitignore
- app/build.gradle.kts
- build.gradle.kts
- Added the dependencies for the project and app gradle files.
- Updated the gitignore in order to keep the API keys private.
> Setting firebase firestore

- .gitignore
- app/build.gradle.kts
- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/MapViewModel.kt
- build.gradle.kts
- updated `.gitignore` to include secrets.properties on ignore list
- updated main activity which had an unused dependency (commented it out. Not clean, but will do for the time being)
- changed a firestore collection name which was causing errors for no apparent reason. Not clean, but will do for the time being
- updated `build.gradle.kts` to have all needed dependencies for building the problem. Some were lost during merging, this should be fixed now.
> Updated project structure so that it builds on main

- app/src/main/java/com/github/wanderwise_inc/app/ui/signin/LoginScreen.kt
Just navigates on sign-in failure. Will do for now until we are able to fix it
> added bandaid fix for login problem

- app/build.gradle.kts
- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/map/MapScreen.kt
> created the mapView using the example from the maps compose doc

- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/ItineraryPreferences.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/Location.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/Tag.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/MapViewModel.kt
Added preference-based filtering of itineraries
- `Tag` type (`String`) that represents an itinerary tag, with an `object` containing common instances
- updated `Itinerary` with a list of tags, as well as upvotes / downvotes. Added a scoring method that scores an itinerary based on preferences, as well as overall rating
- implemented preference-based filtering, and sorting based on scoring in `MapViewModel`
- Added a function for computing distance between two `Location`s (goal is to use for sorting in the future)
- Added some no-argument constructors which are needed by firebase
- did some general refactoring for prettier code uwu
> Updates to tinerary backend

- app/src/androidTest/java/com/github/wanderwise_inc/app/model/LocationTest.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/Location.kt
- Unit tests for `Location` class
> Added tests for Location

- app/src/main/java/com/github/wanderwise_inc/app/ui/liked/LikedScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/map/MapScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/BottomNavigationMenu.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/overview/OverviewScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/search/SearchScreen.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
Updated tests for navigation between composable while signed in, verifying that the bottom navigation bar works correctly.
> added tests for updated navigation

- app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
- Fixed home screen tests
- ran ktfmt
- uwu
> Was able to fix HomeScreen tests

- README.md
The new README contains detailed workflow guidelines to enhance our project management and development practices.
> workflow guidelines 

- app/src/main/java/com/github/wanderwise_inc/app/DemoSetup.kt
- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/OverviewScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/HomeNavGraph.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
Called in `HomeNavGraph` file. Can be easily removed by just not calling the function `demoSetup()` and app still works
- Creates some itineraries and adds them to `mapViewModel`
- creates some profiles and adds them to `profileViewModel`
> Isolated demo setup in one new file

- app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
- Added `ProfilePictureWithDropDown` composable called by `ProfileScreen`
- Added nullability of `profile` argument + null check to `ProfilePictureChangeDropdownMenu`
This fixes the endless 404 loop addressed by #138 and centralizes the `ProfilePicture` composable.
`ProfilePictureChangeDropdownMenu` is interacting with `imageRepository` directly. This isn't best practice, and it should probably be going through `profileViewModel` instead.
> fixed `ProfileScreen` which was depending on a deprecated implementation of `ProfilePicture`

- app/src/main/java/com/github/wanderwise_inc/app/ui/theme/Theme.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/ThemeTest.kt
Testing:
- Colors 
- Typography
- Light and Dark modes
achieving 88% line coverage over the ... ui.theme package
> Wrote tests for the WanderWise Theme

- app/src/main/java/com/github/wanderwise_inc/app/ui/search/ChipsModel.kt
> upgraded chips

- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/data/SignInRepository.kt
- app/src/main/java/com/github/wanderwise_inc/app/data/SignInRepositoryImpl.kt
- app/src/main/java/com/github/wanderwise_inc/app/di/AppModule.kt
- app/src/test/java/com/github/wanderwise_inc/app/data/SignInRepositoryTest.kt
- Extract SignInRepositoryImpl in its own class
- Remove result and resultCode attributes
- Update comments
- Update tests
- Remove tests that are no longer pertinent
- 97% line coverage
- Result checks done in signInLauncher function
> Refactor SignInRepository

- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/MapViewModel.kt
> added setters for title and description for itinerary creation

- app/src/main/java/com/github/wanderwise_inc/app/DemoSetup.kt
- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/CreateItineraryMap.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/CreationScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/home/HomeScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/ItineraryList.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/list_itineraries/OverviewScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/HomeNavGraph.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/navigation/graph/RootNavGraph.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/profile/ProfileScreen.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/CreateItineraryViewModel.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModel.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/list_itineraries/LikedScreenTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/list_itineraries/OverviewScreenTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/list_itineraries/ScrollableItineraryListTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/map/PreviewItineraryScreenKtTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/navigation/HomeNavigationTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModelTest.kt
- Renamed the  `MapViewModel` to `ItineraryViewModel`
- Created a specific View Model for itinerary creation called `CreateItineraryViewModel`
> I refactored the late `MapViewModel`:

- app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/TestTags.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepPreview.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/popup/HintPopup.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/CreateItineraryViewModel.kt
- app/src/test/java/com/github/wanderwise_inc/app/model/location/ItineraryTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepPreviewKtTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/viewmodel/CreateItineraryViewModelTest.kt
Implemented the logic/response behind the finish button 
- when clicking on the button, checks if every field has been set (!= ItineraryDefaultValue.FIELD)
- if they have all been set, the function uploadNewItinerary is called and navigates to Profile screen
- if some fields haven't been set, a popup notification appears notifying the user of all the unset fields
A few remarks: 
- I used ItineraryDefaultValue and not null because, otherwise we would have had issues with the builder setters implementation. 
- test have been written (since the code spans multiple files I don't know how much coverage I have on new code)
> Itinerary creation finish button logic implemented

- app/src/main/java/com/github/wanderwise_inc/app/model/location/Location.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreateItineraryMap.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
- app/src/test/java/com/github/wanderwise_inc/app/model/LocationTest.kt
- app/src/test/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClientTest.kt
Quick fix to a problem where placed markers did not correctly display in the list of locations
> Fix/create locations place marker UI

- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreationStepChooseTags.kt
this is a very minor pull request that updated the CreationTagsScreen work correctly. 
The screen is still not perfect but should at leas work as intended...
> tags screen still problematic but pretty much works

- .github/workflows/ci.yml
The CI run on tag push to make release.
Here is how to make a release (for M4)
On the branch you want to release (main or latest version):
- git tag <tag_name> (if you want release M4, replace <tag_name> by M4)
- git push origin <tag_name>
On github
- Go to the release section
- Click on the "Tags" section
- Click on your <tag_name>
- Click on "Create release from tag" 
- Upload the apk by clicking on "Attach binaries by dropping them here or selecting them"
- Finally click on "Publish the release" to do exactly that
You can download the zip apk at the bottom of our (many) successful CI
and dont forget to unzip it before uploading it :)
That's it folks hope you enjoyed the reading !
> CI on tag push

- app/src/main/java/com/github/wanderwise_inc/app/data/DirectionRepositoryImpl.kt
- app/src/main/java/com/github/wanderwise_inc/app/data/ItineraryRepositoryImpl.kt
- app/src/main/java/com/github/wanderwise_inc/app/disk/ItineraryProtoSerializer.kt
- app/src/main/java/com/github/wanderwise_inc/app/disk/SavedItinerariesSerializer.kt
- app/src/main/java/com/github/wanderwise_inc/app/model/location/Itinerary.kt
- app/src/main/java/com/github/wanderwise_inc/app/network/DirectionsApiService.kt
- app/src/main/java/com/github/wanderwise_inc/app/util.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/CreateItineraryViewModel.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ItineraryViewModel.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ProfileViewModel.kt
- app/src/main/proto/itinerary.proto
Added some documentation to functions that I wrote, and some that I didn't write but am familiar with.
> Added documentation to some files

- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/ContextExt.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LocationClient.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/UserLocationClient.kt
> Comment `LocationClient` and its implementation

- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LoginViewModel.kt
> Comment `LoginViewModel` 

- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
> Comment `MainActivity`

- app/src/main/java/com/github/wanderwise_inc/app/data/GoogleSignInLauncher.kt
- app/src/main/java/com/github/wanderwise_inc/app/di/AppModule.kt
> Comment `AppModule` + Rename some properties

- app/src/main/java/com/github/wanderwise_inc/app/data/GoogleSignInLauncher.kt
- app/src/main/java/com/github/wanderwise_inc/app/data/SignInLauncher.kt
Title says it all.
I followed the recommended commentary format for KDoc.
> Comment `SignInLauncher` interface and its implementation

- app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/CreateItineraryE2ETest.kt
- app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/LikeE2ETest.kt
- app/src/androidTest/java/com/github/wanderwise_inc/app/e2e/PreviewItineraryE2ETest.kt
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/github/wanderwise_inc/app/LocationApp.kt
- app/src/main/java/com/github/wanderwise_inc/app/MainActivity.kt
- app/src/main/java/com/github/wanderwise_inc/app/data/GoogleSignInLauncher.kt
- app/src/main/java/com/github/wanderwise_inc/app/ui/creation/steps/CreateItineraryMap.kt
- app/src/main/java/com/github/wanderwise_inc/app/viewmodel/LocationService.kt
When the user click on the "Start" button to track his position to create an itinerary, a notification is now displayed to show that he is currently being tracked. The notification disappear after clicking the "Stop" button.
> Show notification when tracking to create an itinerary
